name: cloudsaver
services:
  cloudsaver:
    image: jiangrui1994/cloudsaver:latest
    container_name: cloudsaver
    ports:
      - "8008:8008"
    volumes:
      - /DATA/AppData/cloudsaver/data:/app/data
      - /DATA/AppData/cloudsaver/config:/app/config
    restart: unless-stopped
    deploy:
      resources:
        reservations:
          memory: 256M

x-casaos:
  id: com.cp0204.cloudsaver
  architectures:
    - amd64
    - arm64
  main: cloudsaver
  store_app_id: cloudsaver
  author: Cp0204
  category: Productivity
  description:
    en_US: CloudSaver is a web disk resource search and transfer tool. It supports responsive layout and is perfectly adapted to mobile and PC. It can be deployed with one click through Docker.
    zh_CN: 一款网盘资源搜索与转存工具，支持响应式布局，移动端与PC完美适配，可通过 Docker 一键部署。
  developer: jiangrui1994
  icon: https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/cloudsaver/icon.svg
  screenshot_link:
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/cloudsaver/screenshot-1.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/cloudsaver/screenshot-2.png
    - https://cdn.jsdelivr.net/gh/Cp0204/CasaOS-AppStore-Play@main/Apps/cloudsaver/screenshot-3.png
  tagline:
    en_US: A web disk resource search and transfer tool
    zh_CN: 一款网盘资源搜索与转存工具
  tips:
    before_install:
      en_US: |
        Default registration code
        - Administrator: 230713
        - Regular user: 9527
      zh_CN: |
        1. 资源搜索需要配置代理环境
        2.默认注册码
          - 管理员：230713
          - 普通用户：9527
  title:
    en_US: CloudSaver
  index: /
  port_map: "8008"
